In [2]:
import numpy as np 

# Numpy array

In [3]:
benimListem = [20,30,40]

In [4]:
type(benimListem)

list

In [7]:
np.array(benimListem)

numpy.ndarray

In [6]:
type(benimListem)

list

In [8]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
type(matrixListesi)

list

In [10]:
matrixListesi[1]

[20, 30, 40]

In [11]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange

In [12]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# ones

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [26]:
np.linspace(0,20,5)

In [30]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

# eye

In [31]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [34]:
np.random.randn(50)

array([ 1.5647771 ,  0.41343039, -0.67362093,  0.6834027 ,  0.71237453,
       -0.67660571, -0.27548896, -1.25877052, -0.40243698, -0.9176261 ,
        0.64403135, -0.32183354,  0.51726487,  0.31454954, -0.86224868,
        0.71612384, -0.53244029,  0.46605928,  0.66299565, -0.32134536,
        0.14636869,  0.39240593,  0.55345055,  1.1639484 , -1.28031128,
       -1.34766629,  1.7738512 , -0.14803462,  0.76265499, -0.08372038,
       -0.09468655, -0.64653331,  1.25501379,  0.47946155, -0.67649068,
       -1.62650303, -0.17534305,  0.50522652,  0.44540579, -0.9546074 ,
       -0.76286798,  1.4145732 , -0.46379297, -0.63274965, -0.52347529,
       -0.30688285, -0.53756444,  1.82024071, -0.8180907 ,  0.43218123])

In [36]:
np.random.randn(4,4)

array([[ 1.45713372, -0.45917721,  0.9824316 , -1.98779173],
       [-0.28763654,  1.29775888, -0.11912829,  0.59505955],
       [ 0.92639694,  0.42157131,  1.31694247,  0.93366518],
       [-0.38302023, -1.66017744, -2.06202342,  0.05571531]])

In [48]:
np.random.randint(0,101) # son rakamı aralığa dahil etmiyor. 

3

In [49]:
np.random.randint(1,10,3)

array([9, 2, 6])

In [50]:
benimNumpyDizim = np.arange(30)

In [51]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
benimRandomDizim = np.random.randint(0,100,30)

In [55]:
benimRandomDizim

array([65,  3, 15, 83, 33, 18,  1, 50, 91, 36,  9, 41,  9, 76, 32, 45, 35,
       50, 29, 88, 81, 69, 49, 94, 37, 93, 64, 89, 70,  4])

# Numpy Dizi Metodları

In [58]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
benimNumpyDizim.max()

29

In [60]:
benimNumpyDizim.mean()

14.5

In [61]:
benimNumpyDizim.min()

0

In [62]:
benimNumpyDizim.argmax()

29

In [63]:
benimNumpyDizim.argmin()

0

In [64]:
benimNumpyDizim.shape

(30,)

In [65]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [66]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])