In [1]:
import numpy as np 

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:5] # son indeksi içeri katmıyor

array([3, 4])

In [11]:
benimDizim[3:8] = -5

In [12]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
baskaDizi = np.arange(0,24)

In [22]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
slicingDizi = baskaDizi[4:9] 

In [24]:
slicingDizi

array([4, 5, 6, 7, 8])

In [19]:
slicingDizi = 700

In [25]:
type(slicingDizi)

numpy.ndarray

In [27]:
slicingDizi[:] = 700

In [28]:
slicingDizi

array([700, 700, 700, 700, 700])

In [29]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [30]:
ornekDizi= np.arange(0,24)

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
ornekDiziKopyası = ornekDizi.copy()

In [33]:
ornekDiziKopyasıSlicing = ornekDiziKopyası[3:6]

In [34]:
ornekDiziKopyasıSlicing[:] = 800

In [35]:
ornekDiziKopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [36]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
ornekDiziKopyasıSlicing

array([800, 800, 800])

# matrix

In [38]:
benimListem = [[10,20,30],[20,30,40],[30,40,50]]

In [39]:
benimMatrixDizim = np.array(benimListem)

In [40]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [41]:
benimMatrixDizim[0]

array([10, 20, 30])

In [42]:
benimMatrixDizim[1][2]

40

In [43]:
benimMatrixDizim[1,2]

40

In [44]:
benimMatrixDizim[1:,2]

array([40, 50])

In [45]:
benimMatrixDizim[0:,2]

array([30, 40, 50])

In [46]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [47]:
yeniMatrix = np.array(yeniListe)

In [48]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# operasyonlar

In [54]:
yeniDizi = np.random.randint(1,100,20)

In [55]:
yeniDizi

array([38, 33, 24, 71, 42, 14, 71, 25,  3, 34, 38, 45, 70, 97, 56, 18,  7,
        3, 88,  3])

In [56]:
yeniDizi>24

array([ True,  True, False,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False])

In [58]:
yeniDizi

array([38, 33, 24, 71, 42, 14, 71, 25,  3, 34, 38, 45, 70, 97, 56, 18,  7,
        3, 88,  3])

In [59]:
sonucDizisi = yeniDizi> 24

In [60]:
sonucDizisi

array([ True,  True, False,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False])

In [61]:
yeniDizi

array([38, 33, 24, 71, 42, 14, 71, 25,  3, 34, 38, 45, 70, 97, 56, 18,  7,
        3, 88,  3])

In [63]:
yeniDizi[sonucDizisi] # True değerlerini veriyor ! 

array([38, 33, 71, 42, 71, 25, 34, 38, 45, 70, 97, 56, 88])

In [69]:
yeniDizi

array([38, 33, 24, 71, 42, 14, 71, 25,  3, 34, 38, 45, 70, 97, 56, 18,  7,
        3, 88,  3])

In [72]:
yeniDizi[yeniDizi > 24]

array([38, 33, 71, 42, 71, 25, 34, 38, 45, 70, 97, 56, 88])

In [73]:
sonDizi = np.arange(0,24)

In [74]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [76]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [77]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [79]:
sonDizi / sonDizi # 0/0 değerinden dolayı nan değeri atanıyor, ancak sonuç veriyor.

C:\Users\burak\AppData\Local\Temp/ipykernel_14480/3484886457.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi # 0/0 değerinden dolayı nan değeri atanıyor, ancak sonuç veriyor.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [81]:
np.max(sonDizi)

23

In [82]:
np.min(sonDizi)

0